#!/usr/bin/ruby
# Do chef deploy from Jenkins



Dir.chdir(File.dirname(__FILE__))
load 'common_tasks'

before :invoke do
  set_core_variables
  set_role
end


task :invoke do
        run " sudo chef-client --color -Fdoc"

end
